In [2]:
from __future__ import print_function, division
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')
from bokeh.plotting import figure, show, output_notebook, output_file
from bokeh.models import ColumnDataSource, Range1d

output_notebook()

DyCE Model consists of data curated from 43 papers, most of which are in fact review articles.

In [37]:
pmids = pd.read_csv('/Users/Gully/Documents/Projects/2_active/bigMech/work/2016-08-22-dyceModel/dyce_model_pmids.tsv',
                 sep='\t')

pmids['count'] = pd.Series(1, index=pmids.index)
print(pmids)

        pmid review  n_references  count
0   10228013      n            54      1
1   10602461      y           321      1
2   10708950      y            85      1
3   10878024      n            62      1
4   11170294      y            94      1
5   11312109      y            69      1
6   11790550      y            63      1
7   11920677      y           226      1
8   12007403      n            54      1
9   12074877      y            24      1
10  12401408      y            74      1
11  12835716      y           569      1
12   1386364      n            43      1
13  14707283      y           111      1
14  14762439      n            39      1
15  15255771      y           172      1
16  15489911      y           235      1
17  15527798      n            20      1
18  15735721      n            59      1
19  16377102      y           135      1
20  16839880      n            43      1
21  16887934      y            52      1
22  17304234      y            90      1
23  17446563      n            51      1
24  17502367      y            69      1
25  17717517      y            99      1
26  18485876      n            41      1
27  19292888      y            24      1
28  19498381      y           145      1
29  21498522      y           125      1
30  22084445      y            35      1
31  22168436      y           233      1
32  22273505      y           181      1
33  23339455      n            41      1
34  23343194      y           157      1
35  23543766      y           176      1
36  23838007      y           189      1
37  24096196      n            21      1
38  25599615      y            71      1
39  26086143      y           125      1
40  26952810      n            45      1
41   7514165      n            22      1
42   7514175      n            35      1
43   8046239      n            80      1
44   8702885      n            71      1
45   9597127      y           132      1

In [42]:
pivot_ref_count = pd.pivot_table(pmids, values='n_references', 
                         index=['pmid'], columns=['review'], 
                         margins=True, aggfunc=np.sum)
pivot_ref_count

review        n       y     All
pmid
1386364    43.0     NaN    43.0
7514165    22.0     NaN    22.0
7514175    35.0     NaN    35.0
8046239    80.0     NaN    80.0
8702885    71.0     NaN    71.0
9597127     NaN   132.0   132.0
10228013   54.0     NaN    54.0
10602461    NaN   321.0   321.0
10708950    NaN    85.0    85.0
10878024   62.0     NaN    62.0
11170294    NaN    94.0    94.0
11312109    NaN    69.0    69.0
11790550    NaN    63.0    63.0
11920677    NaN   226.0   226.0
12007403   54.0     NaN    54.0
12074877    NaN    24.0    24.0
12401408    NaN    74.0    74.0
12835716    NaN   569.0   569.0
14707283    NaN   111.0   111.0
14762439   39.0     NaN    39.0
15255771    NaN   172.0   172.0
15489911    NaN   235.0   235.0
15527798   20.0     NaN    20.0
15735721   59.0     NaN    59.0
16377102    NaN   135.0   135.0
16839880   43.0     NaN    43.0
16887934    NaN    52.0    52.0
17304234    NaN    90.0    90.0
17446563   51.0     NaN    51.0
17502367    NaN    69.0    69.0
17717517    NaN    99.0    99.0
18485876   41.0     NaN    41.0
19292888    NaN    24.0    24.0
19498381    NaN   145.0   145.0
21498522    NaN   125.0   125.0
22084445    NaN    35.0    35.0
22168436    NaN   233.0   233.0
22273505    NaN   181.0   181.0
23339455   41.0     NaN    41.0
23343194    NaN   157.0   157.0
23543766    NaN   176.0   176.0
23838007    NaN   189.0   189.0
24096196   21.0     NaN    21.0
25599615    NaN    71.0    71.0
26086143    NaN   125.0   125.0
26952810   45.0     NaN    45.0
All       781.0  4081.0  4862.0

In [47]:
pivot_count = pd.pivot_table(pmids, values='count',  columns=['review'], index=['pmid'],
                         margins=True, aggfunc=np.sum)

review       n     y   All
pmid
1386364    1.0   NaN   1.0
7514165    1.0   NaN   1.0
7514175    1.0   NaN   1.0
8046239    1.0   NaN   1.0
8702885    1.0   NaN   1.0
9597127    NaN   1.0   1.0
10228013   1.0   NaN   1.0
10602461   NaN   1.0   1.0
10708950   NaN   1.0   1.0
10878024   1.0   NaN   1.0
11170294   NaN   1.0   1.0
11312109   NaN   1.0   1.0
11790550   NaN   1.0   1.0
11920677   NaN   1.0   1.0
12007403   1.0   NaN   1.0
12074877   NaN   1.0   1.0
12401408   NaN   1.0   1.0
12835716   NaN   1.0   1.0
14707283   NaN   1.0   1.0
14762439   1.0   NaN   1.0
15255771   NaN   1.0   1.0
15489911   NaN   1.0   1.0
15527798   1.0   NaN   1.0
15735721   1.0   NaN   1.0
16377102   NaN   1.0   1.0
16839880   1.0   NaN   1.0
16887934   NaN   1.0   1.0
17304234   NaN   1.0   1.0
17446563   1.0   NaN   1.0
17502367   NaN   1.0   1.0
17717517   NaN   1.0   1.0
18485876   1.0   NaN   1.0
19292888   NaN   1.0   1.0
19498381   NaN   1.0   1.0
21498522   NaN   1.0   1.0
22084445   NaN   1.0   1.0
22168436   NaN   1.0   1.0
22273505   NaN   1.0   1.0
23339455   1.0   NaN   1.0
23343194   NaN   1.0   1.0
23543766   NaN   1.0   1.0
23838007   NaN   1.0   1.0
24096196   1.0   NaN   1.0
25599615   NaN   1.0   1.0
26086143   NaN   1.0   1.0
26952810   1.0   NaN   1.0
All       17.0  29.0  46.0